dist: trusty
sudo: false

language: java

jdk:
  - openjdk8

# command to run tests
script:
 - git clone https://github.com/geneontology/minerva.git
 - cd minerva
 - git checkout gene-product-type-updater
 - ./build-cli.sh
 - cd minerva-cli/
 - pwd
 - ls ../../
 - bin/minerva-cli.sh --validate-go-cams -c ../../ontology/catalog-for-validation.xml -s ../../shapes/go-cam-shapes.shex -m ../../shapes/go-cam-shapes.shapeMap -i ../../test_ttl/go_cams/should_pass/ -r ./shape_report_shouldpass.txt -e ./shape_explanation_shouldpass.txt -travis
 - bin/minerva-cli.sh --validate-go-cams -c ../../ontology/catalog-for-validation.xml -s ../../shapes/go-cam-shapes.shex -m ../../shapes/go-cam-shapes.shapeMap -i ../../test_ttl/go_cams/should_fail/ -r ./shape_report_shouldfail.txt -e ./shape_explanation_shouldfail.txt -travis -shouldfail
