dist: trusty
sudo: false

language: python
python:
  - "3.6"

env:
  - COLUMNS=80

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: 
  - python -m unittest tests/test_*.py

