dist: trusty
sudo: false

language: java

jdk:
  - openjdk8

# command to run tests
script: 
 - git clone https://github.com/geneontology/minerva.git
 - cd minerva
 - git checkout add-validation-framework-as-package
 - ./build-cli.sh
 - cd minerva-cli/
 - bin/minerva-cli.sh --validate-go-cams -t -s ../../shapes/go-cam-shapes.shex -m ../../shapes/go-cam-shapes.shapeMap -f ../../test_ttl/go_cams/should_pass/ -e -r ./shape_report.txt
 - bin/minerva-cli.sh --validate-go-cams -t -shouldfail -s ../../shapes/go-cam-shapes.shex -m ../../shapes/go-cam-shapes.shapeMap -f ../../test_ttl/go_cams/should_fail/ -e -r ./shape_report.txt